/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'moctale-dark': '#121212',
        'moctale-accent': '#E50914', 
        "tertiary-fixed": "#56feb8",
        "surface-bright": "#3a3939",
        "on-tertiary-fixed": "#002113",
        "on-tertiary-container": "#e1ffeb",
        "outline-variant": "#4c4354",
        "tertiary": "#2ce19d",
        "surface-dim": "#131313",
        "on-surface": "#e5e2e1",
        "on-primary-fixed": "#2a0054",
        "on-primary-container": "#fef5ff",
        "primary-container": "#9344f2",
        "on-error": "#690005",
        "primary-fixed-dim": "#d9b9ff",
        "on-primary": "#450086",
        "on-secondary-fixed-variant": "#5a00c5",
        "tertiary-container": "#008258",
        "surface-tint": "#d9b9ff",
        "background": "#131313",
        "surface-container": "#201f1f",
        "on-secondary-container": "#dcc8ff",
        "on-error-container": "#ffdad6",
        "on-background": "#e5e2e1",
        "inverse-surface": "#e5e2e1",
        "surface-container-lowest": "#0e0e0e",
        "on-secondary": "#3f008d",
        "surface-container-high": "#2a2a2a",
        "secondary-fixed-dim": "#d3bbff",
        "outline": "#978da0",
        "secondary": "#d3bbff",
        "on-primary-fixed-variant": "#6300bb",
        "inverse-on-surface": "#313030",
        "primary-fixed": "#eedcff",
        "surface-variant": "#353534",
        "surface-container-low": "#1c1b1b",
        "secondary-container": "#7202f4",
        "inverse-primary": "#7e29dd",
        "on-secondary-fixed": "#250059",
        "tertiary-fixed-dim": "#2ce19d",
        "on-surface-variant": "#cec2d7",
        "error-container": "#93000a",
        "primary": "#d9b9ff",
        "on-tertiary-fixed-variant": "#005236",
        "error": "#ffb4ab",
        "surface": "#131313",
        "surface-container-highest": "#353534",
        "secondary-fixed": "#ebddff",
        "on-tertiary": "#003824"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "display": ["Space Grotesk", "sans-serif"],
        "body": ["Space Grotesk", "sans-serif"],
        "brand": ["Kicaps", "Space Grotesk", "sans-serif"],
        "label": ["Courbe Sans", "Space Grotesk", "sans-serif"],
        "sans": ["Space Grotesk", "system-ui", "sans-serif"]
      }
    },
  },
  plugins: [],
}